Домашнее задание №2
Frayko/FocusStartHomeworks pull request #2
Opened 2021-11-05 20:56 UTC by Frayko

Во время выполнения ДЗ был создан workspace с двумя проектами (из первого и второго дз), а также реализован и протестирован класс потокобезопасной коллекции ThreadSafeArray. Плюс добавил .editorconfig, где пометил размер табов по умолчанию 4.

2021-11-05 21:00 UTC, Frayko commented
В main'е вроде как поехали табы, но если открыть сам файл (или в том же XCode), то отображается корректно. Очень странно.

2021-11-07 07:48 UTC, AlexRaptor requested changes

2021-11-07 07:48 UTC, AlexRaptor commented on ThreadSafeArray/ThreadSafeArray/ThreadSafeArray.swift
> +			self.items.count == 0
А чего не `self.items.isEmpty`?

2021-11-07 07:48 UTC, AlexRaptor commented on ThreadSafeArray/ThreadSafeArray/ThreadSafeArray.swift
> +		isolationQueue.sync {
А нужно ли оборачивание в очередь для чтения?

2021-11-07 07:48 UTC, AlexRaptor commented on ThreadSafeArray/ThreadSafeArray/ThreadSafeArray.swift
> +		if index >= 0 && index < self.count {
После проверки до входа в барьер count может измениться (что очень легко проверяется) и словим fatal error выхода за пределы массива

2021-11-07 07:48 UTC, AlexRaptor commented on ThreadSafeArray/ThreadSafeArray/ThreadSafeArray.swift
> +			if index >= 0 && index < self.count {
а вот здесь бы я наплевал на проверки - у эпплового массива из тоже нету

2021-11-08 04:56 UTC, AlexRaptor requested changes

2021-11-08 04:56 UTC, AlexRaptor commented on ThreadSafeArray/ThreadSafeArray/ThreadSafeArray.swift
> +		self.items.count
Я задал вопрос о целесообразности оборачивания чтения в очередь, т.к. у меня были сомнения... но похоже, что правильно делать это в очереди. Может возникнуть следущая ситуация: мы добавляем (append) элемент в массив, и система начинает его расширять со всеми вытекающими типа выделения новой области памяти. И может получиться так, что мы попытаемся запросить, например кол-во элементов, ещё по старому адресу...

2021-11-08 04:56 UTC, AlexRaptor commented on ThreadSafeArray/ThreadSafeArray/ThreadSafeArray.swift
> +		self.items.count
Так что, прошу прощения за введение в заблуждение. Верни - было правильно.

2021-11-08 04:56 UTC, AlexRaptor commented on ThreadSafeArray/ThreadSafeArray/ThreadSafeArray.swift
> +		isolationQueue.async(flags: .barrier) {
А вот здесь, я не могу придумать, зачем нам это может понадобиться. Ну проинициализируем мы нашу коллекцию из разных потоком - получим на выходе 2 разных коллекции.

2021-11-08 07:18 UTC, Frayko commented on ThreadSafeArray/ThreadSafeArray/ThreadSafeArray.swift
> +		isolationQueue.async(flags: .barrier) {
Исправил на возможно добавляемые элементы через "content: T..."

2021-11-08 14:11 UTC, AlexRaptor requested changes
В общем смотри, какая ситуация в простейшем случае... Итераторы являются потоко-безопасными за счёт того, что они итерируются по копии коллекции, которая создаётся в момент инициализации итератора. А после создания итератора можно с коллекцией делать всё, что хочешь - в итераторе останется своя неизменная копия.
выполни следующий код:
```
var array = [Int]()
for number in 0...9 {
	array.append(number)
}
for item in array {
	if item == 3 {
		array.insert(999, at: 9)
	}
	print(item)
}
print(array)
```
и увидишь, что в массив добавилось число 999, но в цикле итерирования оно не появляется, т.к. итерирование производится по копии первоначального массива.
Т.е. для итератора не нужно заморачиваться с потоко-безопасностью.

P.S. могу предположить, что существуют какие-то многопоточные итераторы, но я про них не слыхал

2021-11-08 14:11 UTC, AlexRaptor commented on ThreadSafeArray/ThreadSafeArray/ThreadSafeArray.swift
> +		isolationQueue.async(flags: .barrier) {
Не, я про барьерную таску в ините. Ну не можем мы вызвать инициализацию одного и того же объекта хоть из миллиона потоков - мы просто миллион разных объектов получим. Т.е. не нужен нам там барьер - там он даже и не сработает, потому что для каждого объекта создастся своя индивидуальная `isolationQueue`

2021-11-08 14:11 UTC, AlexRaptor commented on ThreadSafeArray/ThreadSafeArray/ThreadSafeArray.swift
> +		isolationQueue.sync {
Нужно :)

2021-11-08 14:11 UTC, AlexRaptor commented on ThreadSafeArray/ThreadSafeArray/ThreadSafeArray.swift
> +			self.currentIndex += 1
это изменение не потоко-безопасно

2021-11-08 14:11 UTC, AlexRaptor commented on ThreadSafeArray/ThreadSafeArray/ThreadSafeArray.swift
> +		isolationQueue.async(flags: .barrier) {
здесь тоже вряд ли нужно в очередь помещать

2021-11-08 15:22 UTC, Frayko commented on ThreadSafeArray/ThreadSafeArray/ThreadSafeArray.swift
> +		isolationQueue.async(flags: .barrier) {
Да, потестил по-разному добавления вместе с инициализацией в одном асинхронном потоке и пришёл к выводу, что добавление в очередь в принципе не нужно, всё будет работать и так

2021-11-08 17:40 UTC, AlexRaptor approved these changes
👍

2021-11-08 17:56 UTC, merged