Домашнее задание №3
Frayko/FocusStartHomeworks pull request #3
Opened 2021-11-16 15:31 UTC by Frayko

Во время выполнения домашнего задания был реализован графический интерфейс приложения визитки. Опоздал по срокам. Вдоволь помучался с добавлением ScrollView в свой проект, потратил очень много времени на чтение статей. Разобрался, по итогу проблема была лишь в том, что я сначала настраивал ScrollView и только потом добавлял UI элементы, а нужно было это делать наоборот)

2021-11-16 15:35 UTC, Frayko commented
Ну и также не разделил выполнение этапов ДЗ на несколько коммитов, в следующих ДЗ учту это

2021-11-17 07:58 UTC, c0dedbear requested changes
Неплохая работа, но в некоторых моментах перемудрил. + от меня за использование протоколов.

Смотри комменты.

2021-11-17 07:58 UTC, c0dedbear commented on myCV/myCV/Application/AppDelegate.swift
> +		return UIDevice.current.userInterfaceIdiom == .phone ? .portrait : .portrait
а зачем условие если при любом раскладе используем .portrait?

2021-11-17 07:58 UTC, c0dedbear commented on myCV/myCV/Application/DataMapper.swift
> +import Foundation
вроде лишний импорт, и в других местах глянь.

2021-11-17 07:58 UTC, c0dedbear commented on myCV/myCV/Application/DataMapper.swift
> +final class DataMapper {
че т перемудрил ты, маппинга тут нет никакого да еще этот класс занимается сетанием данных в контроллер

2021-11-17 07:58 UTC, c0dedbear commented on myCV/myCV/Application/ScreensFactory.swift
> +final class ScreensFactory {
не стоит создавать класс чисто для статик свойств.

2021-11-17 08:15 UTC, Frayko commented on myCV/myCV/Application/ScreensFactory.swift
> +final class ScreensFactory {
Тогда получается меняю на структуру?

2021-11-17 09:00 UTC, c0dedbear commented on myCV/myCV/Application/ScreensFactory.swift
> +final class ScreensFactory {
лучше на enum

2021-11-17 16:18 UTC, c0dedbear approved these changes
Принято

2021-11-17 16:19 UTC, merged